name: Notify Slack
description: Send notification of current status to Slack

inputs:
  slack_webhook_url:
    required: true
    description: "Slack webhook url"
  app-environment:
    description: "environment to which the app is being deployed [staging, production, etc]"
    required: true
  pipeline_status:
    description: Collated string of previous status' for this pipeline run
runs:
  using: "composite"
  steps:
    - name: Notify deployment status
      shell: bash
      env:
        PIPELINE_STATUS: ${{ inputs.pipeline_status }}
        JOB_STATUS: ${{ job.status }}
        APP_ENVIRONMENT: ${{ inputs.app-environment }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
      run: |
        if [[ "$PIPELINE_STATUS" =~ "skipped"|"failure" ]] || [[ "$JOB_STATUS" == "failure" ]]; then
          pipelineStatus="failed"
        else
          pipelineStatus="success"
        fi

        environment=$(echo "$APP_ENVIRONMENT" | tr '[:lower:]' '[:upper:]')

        coreMessage="Inquests Internal UI Deployment to $environment has"

        if [ "$pipelineStatus" = "failed" ]; then
          runUrl=https://github.com/ministryofjustice/laa-inquests-internal-ui/actions/runs/$GITHUB_RUN_ID
          message=":exclamation: $coreMessage Failed! :exclamation: \n $runUrl"
        elif [ "$environment" = "STAGING" ] || [ "$environment" = "PROD" ]; then
          releaseUrl=https://github.com/ministryofjustice/laa-inquests-internal-ui/releases/tag/$GITHUB_REF_NAME
          message=":white_check_mark: $coreMessage Succeeded! :white_check_mark: \n $releaseUrl"
        else
          echo "Deployment to $environment succeeded - skipping Slack notification."
          exit 0
        fi

        postBody="{
          \"text\": \"${message}\"
        }"

        curl -X POST -H 'Content-type: application/json' \
          --data "$postBody" \
          --url "$SLACK_WEBHOOK_URL"
